const keyboards = [{
  name: 'KBParadise V60 Type R',
  class: 'KBParadiseV60TypeR',
  switch: 'gateronClear',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'ABS',
  color: 0,
  backlighting: 0,
  size: 60,
  macros: 0,
  rollover: 6,
  price: 99
},
{
  name: 'KBParadise V60',
  class: 'KBParadiseV60',
  switch: 'matiasQuietLinear',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'ABS',
  color: 1,
  backlighting: 0,
  size: 60,
  macros: 0,
  rollover: 6,
  price: 109
},
{
  name: 'KBParadise V60 Vintage',
  class: 'KBParadiseV60Vintage',
  switch: 'matiasQuietLinear',
  colorName: 'Vintage',
  LEDName: '',
  keycaps: 'ABS',
  color: 2,
  backlighting: 0,
  size: 60,
  macros: 0,
  rollover: 6,
  price: 109
},
{
  name: 'KBParadise V80',
  class: 'KBParadiseV80',
  switch: 'matiasQuietLinear',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'ABS',
  color: 1,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 119
},
{
  name: 'KBParadise V80 Dolch',
  class: 'KBParadiseV80Dolch',
  switch: 'matiasQuietLinear',
  colorName: 'Dolch',
  LEDName: '',
  keycaps: 'ABS',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 129
},
{
  name: 'KBParadise V80 Red Dolch',
  class: 'KBParadiseV80DolchRed',
  switch: 'matiasQuietLinear',
  colorName: 'Red Dolch',
  LEDName: '',
  keycaps: 'ABS',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 129
},
{
  name: 'KBParadise V80 Olivette',
  class: 'KBParadiseV80Olivette',
  switch: 'matiasQuietLinear',
  colorName: 'Olivette',
  LEDName: '',
  keycaps: 'ABS',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 129
},
{
  name: 'Qisan Magicforce 68 Backlit',
  class: 'Magicforce68LED2',
  switch: 'cherryMXred',
  colorName: 'White',
  LEDName: 'Blue/Orange',
  keycaps: 'ABS',
  color: 1,
  backlighting: 1,
  size: 65,
  macros: 0,
  rollover: 'Full',
  price: 59.69
},
{
  name: 'Rosewill RK-9000V2 RE',
  class: 'RK9000V2',
  switch: 'cherryMXred',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'ABS',
  color: 0,
  backlighting: 0,
  size: 100,
  macros: 0,
  rollover: 6,
  price: 74.99
},
{
  name: 'Cooler Master MasterKeys S',
  class: 'CMMasterKeysS',
  switch: 'cherryMXred',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 0,
  backlighting: 0,
  size: 80,
  macros: 1,
  rollover: 'Full',
  price: 79.99
},
{
  name: 'Ducky One TKL',
  class: 'DuckyOneTKL',
  switch: 'cherryMXred',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 1,
  backlighting: 0,
  size: 80,
  macros: 1,
  rollover: 'Full',
  price: 89
},
{
  name: 'Ducky One White',
  class: 'DuckyOneWhite',
  switch: 'cherryMXred',
  colorName: 'White',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 89
},
{
  name: 'Corsair K70 LUX',
  class: 'CorsairK70',
  switch: 'cherryMXred',
  colorName: 'Black',
  LEDName: 'Red',
  keycaps: 'ABS',
  color: 0,
  backlighting: 1,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 89.97
},
{
  name: 'G.Skill RIPJAWS KM570 RGB',
  class: 'GSkillKM570RGB',
  switch: 'cherryMXred',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 0,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 94.41
},
{
  name: 'Ducky One',
  class: 'DuckyOne',
  switch: 'cherryMXred',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 1,
  backlighting: 0,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 99
},
{
  name: 'Cooler Master MasterKeys Pro M',
  class: 'CMMasterKeysM',
  switch: 'cherryMXred',
  colorName: 'Black',
  LEDName: 'White',
  keycaps: 'PBT',
  color: 0,
  backlighting: 1,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 99.99
},
{
  name: 'Leopold FC660M',
  class: 'LeopoldFC660M',
  switch: 'cherryMXred',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 1,
  backlighting: 0,
  size: 65,
  macros: 0,
  rollover: 'Full',
  price: 109
},
{
  name: 'Leopold FC660M Beige',
  class: 'LeopoldFC660MBeige',
  switch: 'cherryMXred',
  colorName: 'Beige',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 65,
  macros: 0,
  rollover: 'Full',
  price: 109
},
{
  name: 'Leopold FC660M Grey/Blue',
  class: 'LeopoldFC660MGreyBlue',
  switch: 'cherryMXred',
  colorName: 'Grey/Blue',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 65,
  macros: 0,
  rollover: 'Full',
  price: 109
},
{
  name: 'Leopold FC750R Beige',
  class: 'LeopoldFC750RBeige',
  switch: 'cherryMXred',
  colorName: 'Beige',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 114
},
{
  name: 'Leopold FC750R Grey/Blue',
  class: 'LeopoldFC750RGreyBlue',
  switch: 'cherryMXred',
  colorName: 'Grey/Blue',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 114
},
{
  name: 'Leopold FC750R White/Green',
  class: 'LeopoldFC750RWhiteGreen',
  switch: 'cherryMXred',
  colorName: 'White/Green',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 114
},
{
  name: 'Cooler Master MasterKeys Pro S RGB',
  class: 'CMMasterKeysSRGB',
  switch: 'cherryMXred',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'PBT',
  color: 0,
  backlighting: 2,
  size: 80,
  macros: 1,
  rollover: 'Full',
  price: 115.25
},
{
  name: 'Leopold FC900R',
  class: 'LeopoldFC900R',
  switch: 'cherryMXred',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 1,
  backlighting: 0,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 124
},
{
  name: 'Leopold FC900R Beige',
  class: 'LeopoldFC900RBeige',
  switch: 'cherryMXred',
  colorName: 'Beige',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 124
},
{
  name: 'Leopold FC900R White/Green',
  class: 'LeopoldFC900RWhiteGreen',
  switch: 'cherryMXred',
  colorName: 'White/Green',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 124
},
{
  name: 'Corsair K70 LUX RGB',
  class: 'CorsairK70RGB',
  switch: 'cherryMXred',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 0,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 129.99
},
{
  name: 'Cooler Master MasterKeys MK750 RGB',
  class: 'CMMasterKeysMK750',
  switch: 'cherryMXred',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'PBT',
  color: 0,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 144.24
},
{
  name: 'Corsair K95 RGB PLATINUM',
  class: 'CorsairK95',
  switch: 'cherryMXspeedsilver',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 0,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 159.99
},
{
  name: 'Corsair K95 RGB PLATINUM Gunmetal',
  class: 'CorsairK95Gunmetal',
  switch: 'cherryMXspeedsilver',
  colorName: 'Gunmetal',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 0,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 192.67
},
{
  name: 'Corsair Strafe',
  class: 'CorsairStrafe',
  switch: 'cherryMXSilentRed',
  colorName: 'Black',
  LEDName: 'Red',
  keycaps: 'ABS',
  color: 0,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 79.99
},
{
  name: 'MK Typist C',
  class: 'MKTypist',
  switch: 'cherryMXSilentRed',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 0,
  backlighting: 0,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 109
},
{
  name: 'Leopold FC660M Beige',
  class: 'LeopoldFC660MBeige',
  switch: 'cherryMXSilentRed',
  colorName: 'Beige',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 65,
  macros: 0,
  rollover: 'Full',
  price: 114
},
{
  name: 'Leopold FC750R Beige',
  class: 'LeopoldFC750RBeige',
  switch: 'cherryMXSilentRed',
  colorName: 'Beige',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 124
},
{
  name: 'Leopold FC750R Grey/Blue',
  class: 'LeopoldFC750RGreyBlue',
  switch: 'cherryMXSilentRed',
  colorName: 'Grey/Blue',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 124
},
{
  name: 'Leopold FC750R White/Green',
  class: 'LeopoldFC750RWhiteGreen',
  switch: 'cherryMXred',
  colorName: 'White/Green',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 124
},
{
  name: 'Leopold FC900R Beige',
  class: 'LeopoldFC900RBeige',
  switch: 'cherryMXSilentRed',
  colorName: 'Beige',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 129
},
{
  name: 'Leopold FC900R White/Green',
  class: 'LeopoldFC900RWhiteGreen',
  switch: 'cherryMXSilentRed',
  colorName: 'White/Green',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 129
},
{
  name: 'Vortex POK3R RGB',
  class: 'VortexPOK3RRGB',
  switch: 'cherryMXSilentRed',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 1,
  backlighting: 2,
  size: 60,
  macros: 1,
  rollover: 6,
  price: 139
},
{
  name: 'Vortex POK3R White RGB',
  class: 'VortexPOK3RWhiteRGB',
  switch: 'cherryMXSilentRed',
  colorName: 'White',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 2,
  backlighting: 2,
  size: 60,
  macros: 1,
  rollover: 6,
  price: 139
},
{
  name: 'Vortex POK3R White',
  class: 'VortexPOK3RWhite',
  switch: 'cherryMXSilentRed',
  colorName: 'White',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 60,
  macros: 1,
  rollover: 6,
  price: 139
},
{
  name: 'Filco Majestouch 2',
  class: 'FilcoMajestouch2',
  switch: 'cherryMXSilentRed',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'ABS',
  color: 1,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 139
},
{
  name: 'Filco Majestouch 2 HAKUA',
  class: 'FilcoMajestouch2HAKUA',
  switch: 'cherryMXSilentRed',
  colorName: 'White',
  LEDName: '',
  keycaps: 'ABS',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 139
},
{
  name: 'Qisan Magicforce 68 Backlit',
  class: 'Magicforce68LED',
  switch: 'gateronRed',
  colorName: 'White',
  LEDName: 'White',
  keycaps: 'ABS',
  color: 1,
  backlighting: 1,
  size: 65,
  macros: 0,
  rollover: 'Full',
  price: 62.99
},
{
  name: 'Vortex POK3R RGB',
  class: 'VortexPOK3RRGB',
  switch: 'cherryMXnaturewhite',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 1,
  backlighting: 2,
  size: 60,
  macros: 1,
  rollover: 6,
  price: 139
},
{
  name: 'Vortex POK3R White RGB',
  class: 'VortexPOK3RWhiteRGB',
  switch: 'cherryMXnaturewhite',
  colorName: 'White',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 2,
  backlighting: 2,
  size: 60,
  macros: 1,
  rollover: 6,
  price: 139
},
{
  name: 'Ducky One TKL RGB',
  class: 'DuckyOneRGBTKL',
  switch: 'cherryMXnaturewhite',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'PBT',
  color: 1,
  backlighting: 2,
  size: 80,
  macros: 1,
  rollover: 'Full',
  price: 139
},
{
  name: 'Ducky One White TKL RGB',
  class: 'DuckyOneWhiteRGBTKL',
  switch: 'cherryMXnaturewhite',
  colorName: 'White',
  LEDName: 'RGB',
  keycaps: 'PBT',
  color: 2,
  backlighting: 2,
  size: 80,
  macros: 1,
  rollover: 'Full',
  price: 139
},
{
  name: 'Ducky One RGB',
  class: 'DuckyOneRGB',
  switch: 'cherryMXnaturewhite',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'PBT',
  color: 1,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 139
},
{
  name: 'Ducky One White RGB',
  class: 'DuckyOneWhiteRGB',
  switch: 'cherryMXnaturewhite',
  colorName: 'White',
  LEDName: 'RGB',
  keycaps: 'PBT',
  color: 2,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 139
},
{
  name: 'Qisan Magicforce 108 Backlit',
  class: 'Magicforce108LED',
  switch: 'gateronBlack',
  colorName: 'White',
  LEDName: 'Ice Blue',
  keycaps: 'ABS',
  color: 1,
  backlighting: 1,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 69.99
},
{
  name: 'Ducky One TKL',
  class: 'DuckyOneTKL',
  switch: 'cherryMXblack',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 1,
  backlighting: 0,
  size: 80,
  macros: 1,
  rollover: 'Full',
  price: 89
},
{
  name: 'Ducky One White',
  class: 'DuckyOneWhite',
  switch: 'cherryMXblack',
  colorName: 'White',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 89
},
{
  name: 'Vortex Core',
  class: 'VortexCore',
  switch: 'cherryMXblack',
  colorName: 'Beige',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 40,
  macros: 1,
  rollover: 'Full',
  price: 89
},
{
  name: 'Ducky One',
  class: 'DuckyOne',
  switch: 'cherryMXblack',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 1,
  backlighting: 0,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 99
},
{
  name: 'Ducky One 2 Horizon TKL',
  class: 'DuckyOneHorizonTKL',
  switch: 'cherryMXblack',
  colorName: 'Horizon',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 1,
  rollover: 'Full',
  price: 99
},
{
  name: 'Ducky One 2 Skyline TKL',
  class: 'DuckyOneSkylineTKL',
  switch: 'cherryMXblack',
  colorName: 'Skyline',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 1,
  rollover: 'Full',
  price: 99
},
{
  name: 'Ducky One 2 Horizon',
  class: 'DuckyOneHorizon',
  switch: 'cherryMXblack',
  colorName: 'Horizon',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 99
},
{
  name: 'Ducky One 2 Skyline',
  class: 'DuckyOneSkyline',
  switch: 'cherryMXblack',
  colorName: 'Skyline',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 99
},
{
  name: 'Leopold FC750R White/Green',
  class: 'LeopoldFC750RWhiteGreen',
  switch: 'cherryMXblack',
  colorName: 'White/Green',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 119
},
{
  name: 'Leopold FC900R White/Green',
  class: 'LeopoldFC900RWhiteGreen',
  switch: 'cherryMXblack',
  colorName: 'White/Green',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 124
},
{
  name: 'GANSS GS-87 RGB',
  class: 'GANSS87',
  switch: 'cherryMXblack',
  colorName: 'White',
  LEDName: 'RGB',
  keycaps: 'PBT',
  color: 1,
  backlighting: 2,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 129
},
{
  name: 'GANSS GK-87 RGB',
  class: 'GANSS87',
  switch: 'cherryMXSilentBlack',
  colorName: 'White',
  LEDName: 'RGB',
  keycaps: 'PBT',
  color: 1,
  backlighting: 2,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 119
},
{
  name: 'KBParadise V80 Vintage',
  class: 'KBParadiseV80Vintage',
  switch: 'cherryMXSilentBlack',
  colorName: 'Vintage',
  LEDName: '',
  keycaps: 'ABS',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 119
},
{
  name: 'Cherry G80-3494LTCEU-2 G80-3494',
  class: 'CherrySilentBlack',
  switch: 'cherryMXSilentBlack',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'ABS',
  color: 0,
  backlighting: 0,
  size: 100,
  macros: 0,
  rollover: 6,
  price: 120.47
},
{
  name: 'Varmilo VA87M Panda',
  class: 'VarmiloVA87MPanda',
  switch: 'cherryMXSilentBlack',
  colorName: 'Panda',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 175
},
{
  name: 'Varmilo VA108M Panda',
  class: 'VarmiloVA108MPanda',
  switch: 'cherryMXSilentBlack',
  colorName: 'Panda',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 193
},
{
  name: 'KBParadise V60 Type R',
  class: 'KBParadiseV60TypeR',
  switch: 'cherryMXlineargrey',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'ABS',
  color: 0,
  backlighting: 0,
  size: 60,
  macros: 0,
  rollover: 6,
  price: 105
},
{
  name: 'Vortex One',
  class: 'VortexONE',
  switch: 'cherryMXlineargrey',
  colorName: 'Black',
  LEDName: 'White',
  keycaps: 'ABS',
  color: 1,
  backlighting: 1,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 144
},
{
  name: 'Vortex One White',
  class: 'VortexONEWhite',
  switch: 'cherryMXlineargrey',
  colorName: 'White',
  LEDName: 'Orange',
  keycaps: 'ABS',
  color: 2,
  backlighting: 1,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 144
},
{
  name: 'Plum 87',
  class: 'Plum87',
  switch: 'topre30g',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'POM',
  color: 1,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 149
},
{
  name: 'Plum 87 White',
  class: 'Plum87White',
  switch: 'topre30g',
  colorName: 'White',
  LEDName: '',
  keycaps: 'POM',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 149
},
{
  name: 'Plum 108',
  class: 'Plum108',
  switch: 'topre30g',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'POM',
  color: 1,
  backlighting: 0,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 159
},
{
  name: 'Plum 108 White',
  class: 'Plum108White',
  switch: 'topre30g',
  colorName: 'White',
  LEDName: '',
  keycaps: 'POM',
  color: 2,
  backlighting: 0,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 159
},
{
  name: 'Plum 87 RGB',
  class: 'Plum87WhiteRGB',
  switch: 'topre30g',
  colorName: 'White',
  LEDName: 'RGB',
  keycaps: 'POM',
  color: 1,
  backlighting: 2,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 169
},
{
  name: 'Plum 108 RGB',
  class: 'Plum108WhiteRGB',
  switch: 'topre30g',
  colorName: 'White',
  LEDName: 'RGB',
  keycaps: 'POM',
  color: 1,
  backlighting: 2,
  size: 100,
  macros: 0,
  rollover: 'Full',
  price: 179
},
{
  name: 'Qisan Magicforce 68',
  class: 'Magicforce68',
  switch: 'cherryMXbrown',
  colorName: 'White',
  LEDName: '',
  keycaps: 'ABS',
  color: 1,
  backlighting: 0,
  size: 65,
  macros: 0,
  rollover: 'Full',
  price: 39.98
},
{
  name: 'Rosewill RK-9000V2 BR',
  class: 'RK9000V2',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'ABS',
  color: 0,
  backlighting: 0,
  size: 100,
  macros: 0,
  rollover: 6,
  price: 67.99
},
{
  name: 'Qisan Magicforce 68 Backlit',
  class: 'Magicforce68LED',
  switch: 'cherryMXbrown',
  colorName: 'White',
  LEDName: 'White',
  keycaps: 'ABS',
  color: 1,
  backlighting: 1,
  size: 65,
  macros: 0,
  rollover: 'Full',
  price: 69.99
},
{
  name: 'Cooler Master MasterKeys S',
  class: 'CMMasterKeysS',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 0,
  backlighting: 0,
  size: 80,
  macros: 1,
  rollover: 'Full',
  price: 79.99
},
{
  name: 'G.Skill RIPJAWS KM570 RGB',
  class: 'GSkillKM570RGB',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 0,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 88.77
},
{
  name: 'Ducky One TKL',
  class: 'DuckyOneTKL',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 1,
  backlighting: 0,
  size: 80,
  macros: 1,
  rollover: 'Full',
  price: 89
},
{
  name: 'Vortex Core',
  class: 'VortexCore',
  switch: 'cherryMXbrown',
  colorName: 'Beige',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 40,
  macros: 1,
  rollover: 'Full',
  price: 89
},
{
  name: 'Ducky One',
  class: 'DuckyOne',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 1,
  backlighting: 0,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 99
},
{
  name: 'Cooler Master MasterKeys Pro M',
  class: 'CMMasterKeysM',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: 'White',
  keycaps: 'PBT',
  color: 0,
  backlighting: 1,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 99.99
},
{
  name: 'Vortex POK3R',
  class: 'VortexPOK3R',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'PBT',
  color: 1,
  backlighting: 2,
  size: 60,
  macros: 1,
  rollover: 6,
  price: 119
},
{
  name: 'Vortex POK3R White',
  class: 'VortexPOK3RWhite',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'PBT',
  color: 1,
  backlighting: 2,
  size: 60,
  macros: 1,
  rollover: 6,
  price: 119
},
{
  name: 'Cooler Master MasterKeys Pro S RGB',
  class: 'CMMasterKeysSRGB',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'PBT',
  color: 0,
  backlighting: 2,
  size: 80,
  macros: 1,
  rollover: 'Full',
  price: 119.99
},
{
  name: 'Cooler Master MasterKeys MK750 RGB',
  class: 'CMMasterKeysMK750',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'PBT',
  color: 0,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 147.65
},
{
  name: 'Filco Majestouch Ninja',
  class: 'FilcoMajestouchNinja',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: '',
  keycaps: 'ABS',
  color: 1,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 139
},
{
  name: 'Filco Majestouch 2 HAKUA',
  class: 'FilcoMajestouch2HAKUA',
  switch: 'cherryMXbrown',
  colorName: 'White',
  LEDName: '',
  keycaps: 'ABS',
  color: 2,
  backlighting: 0,
  size: 80,
  macros: 0,
  rollover: 'Full',
  price: 139
},
{
  name: 'Vortex POK3R RGB',
  class: 'VortexPOK3RRGB',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 1,
  backlighting: 2,
  size: 60,
  macros: 1,
  rollover: 6,
  price: 139
},
{
  name: 'Corsair K95 RGB PLATINUM',
  class: 'CorsairK95',
  switch: 'cherryMXbrown',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 0,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 169.99
},
{
  name: 'Tada68',
  class: 'Tada68',
  switch: 'zealiopurple62g',
  colorName: 'Plastic Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 1,
  backlighting: 0,
  size: 65,
  macros: 1,
  rollover: 'Full',
  price: 139
},
{
  name: 'Tada68 (Aluminum Black Case)',
  class: 'Tada68AluminumBlack',
  switch: 'zealiopurple62g',
  colorName: 'Aluminum Black',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 65,
  macros: 1,
  rollover: 'Full',
  price: 210
},
{
  name: 'Tada68 (Aluminum Blue Case)',
  class: 'Tada68AluminumBlue',
  switch: 'zealiopurple62g',
  colorName: 'Aluminum Blue',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 65,
  macros: 1,
  rollover: 'Full',
  price: 210
},
{
  name: 'Tada68 (Aluminum Grey Case)',
  class: 'Tada68AluminumGrey',
  switch: 'zealiopurple62g',
  colorName: 'Aluminum Grey',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 65,
  macros: 1,
  rollover: 'Full',
  price: 210
},
{
  name: 'Tada68 (Aluminum Red Case)',
  class: 'Tada68AluminumRed',
  switch: 'zealiopurple62g',
  colorName: 'Aluminum Red',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 65,
  macros: 1,
  rollover: 'Full',
  price: 210
},
{
  name: 'Tada68 (Aluminum Silver Case)',
  class: 'Tada68AluminumSilver',
  switch: 'zealiopurple62g',
  colorName: 'Aluminum Silver',
  LEDName: '',
  keycaps: 'PBT',
  color: 2,
  backlighting: 0,
  size: 65,
  macros: 1,
  rollover: 'Full',
  price: 210
},
{
  name: 'Redragon K550 YAMA',
  class: 'RedragonK550',
  switch: 'outemuPurple',
  colorName: 'Black',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 1,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 68.99
},
{
  name: 'Redragon K550 YAMA White',
  class: 'RedragonK550White',
  switch: 'outemuPurple',
  colorName: 'White',
  LEDName: 'RGB',
  keycaps: 'ABS',
  color: 2,
  backlighting: 2,
  size: 100,
  macros: 1,
  rollover: 'Full',
  price: 68.99
}];
